name = "simplifile"
version = "2.2.0"
description = "Basic file operations that work on all targets"

licences = ["Apache-2.0"]
repository = { type = "github", user = "bcpeinhardt", repo = "simplifile" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = { path = "../gleam-stdlib" }
filepath = { path = "../gleam-filepath" }

# [dev-dependencies]
# gleeunit = "~> 1.0"
